name: Deployment workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      azure-login:
        required: true

jobs:
  infrastructure-incremental:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-login }}
      - name: Deploy Europe
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment sub create --name europe --location westeurope --template-file ./infrastructure/main.json --parameters ./infrastructure/${{ inputs.environment }}.parameters.json --parameters locationAbbriviation=we
      - name: Deploy United States
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment sub create --name america --location westus --template-file ./infrastructure/main.json --parameters ./infrastructure/${{ inputs.environment }}.parameters.json --parameters locationAbbriviation=us
      - name: Deploy Asia
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment sub create --name asia --location eastasia --template-file ./infrastructure/main.json --parameters ./infrastructure/${{ inputs.environment }}.parameters.json --parameters locationAbbriviation=asi
      - name: Traffic Manager
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment sub create --location westeurope --template-file ./infrastructure/trafficmgr.json --parameters ./infrastructure/${{ inputs.environment }}.parameters.json
