trigger:
  - main

stages:
  - stage: build
    displayName: Publish Bicep Files
    jobs:
      - job: publishbicep
        displayName: Publish bicep files as pipeline artifacts
        steps:
          - template: ./templates/transpile-job.yml

  - stage: deployinfratest
    dependsOn: build
    displayName: Deploy to test
    jobs:
      - job: deploy_us_test
        displayName: Deploy infra to US region test
        steps:
          - template: ./templates/deploy-arm.yml
            parameters:
              seriviceConnectionName: "TestEnvironment"
              location: "westus"
              locationAbbriviation: "us"
              environmentName: "test"

      - job: deploy_eur_test
        displayName: Deploy infra to EUR region test
        dependsOn: deploy_us_test
        steps:
          - template: ./templates/deploy-arm.yml
            parameters:
              seriviceConnectionName: "TestEnvironment"
              location: "westeurope"
              locationAbbriviation: "we"
              environmentName: "test"

      - job: deploy_asia_test
        displayName: Deploy infra to ASIA region test
        dependsOn: deploy_eur_test
        steps:
          - template: ./templates/deploy-arm.yml
            parameters:
              seriviceConnectionName: "TestEnvironment"
              location: "eastasia"
              locationAbbriviation: "asi"
              environmentName: "test"

      - job: deploy_trafficmgr_test
        displayName: Deploy traffic manager test
        dependsOn: deploy_asia_test
        steps:
          - template: ./templates/traffic-manager.yml
            parameters:
              seriviceConnectionName: "TestEnvironment"
              location: "westeurope"
              environmentName: "test"

  - stage: deployinfraprod
    dependsOn: deployinfratest
    displayName: Deploy to production
    jobs:
      - job: deploy_us_prod
        displayName: Deploy infra to US region prod
        steps:
          - template: ./templates/deploy-arm.yml
            parameters:
              seriviceConnectionName: "ProductionEnvironment"
              location: "westus"
              locationAbbriviation: "us"
              environmentName: "prod"

      - job: deploy_eur_prod
        displayName: Deploy infra to EUR region prod
        dependsOn: deploy_us_prod
        steps:
          - template: ./templates/deploy-arm.yml
            parameters:
              seriviceConnectionName: "ProductionEnvironment"
              location: "westeurope"
              locationAbbriviation: "we"
              environmentName: "prod"

      - job: deploy_asia_prod
        displayName: Deploy infra to ASIA region prod
        dependsOn: deploy_eur_prod
        steps:
          - template: ./templates/deploy-arm.yml
            parameters:
              seriviceConnectionName: "ProductionEnvironment"
              location: "eastasia"
              locationAbbriviation: "asi"
              environmentName: "prod"

      - job: deploy_trafficmgr_prod
        displayName: Deploy traffic manager test
        dependsOn: deploy_asia_prod
        steps:
          - template: ./templates/traffic-manager.yml
            parameters:
              seriviceConnectionName: "ProductionEnvironment"
              location: "westeurope"
              environmentName: "prod"
