# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: 'Executing Pester Tests'
  inputs:
    filePath: 'RunPester.ps1'
    arguments: '-ModulePath $(System.DefaultWorkingDirectory)/Chapter 07/Pester -ResultsPath $(System.DefaultWorkingDirectory)\Chapter 07\Pester\Publish -Publish'
    errorActionPreference: 'silentlyContinue'
    ignoreLASTEXITCODE: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/Chapter 07/Pester'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/Pester-Coverage.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)\Chapter 07\Pester\Publish'
    failIfCoverageEmpty: true

- task: PublishTestResults@2
  displayName: 'Publish Pester Tests'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/Test-Pester.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)\Chapter 07\Pester\Publish'
    mergeTestResults: true
    failTaskOnFailedTests: true