trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  displayName: 'Run Pester Unit tests'
  inputs:
    azureSubscription: 'Azure MVP Sponsorship'
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/Chapter 07/Pester/RunPester.ps1'
    ScriptArguments: '-ModulePath "$(System.DefaultWorkingDirectory)/Chapter 07/Pester" -ResultsPath "$(System.DefaultWorkingDirectory)\Chapter 07\Pester\Publish"'
    azurePowerShellVersion: 'LatestVersion'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Chapter 07/Pester'

- task: PublishTestResults@2
  displayName: 'Publish Pester Tests'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/Test-Pester.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)\Chapter 07\Pester\Publish'
    mergeTestResults: true
    failTaskOnFailedTests: true