parameters:
  seriviceConnectionName: ""
  systemName: "demodeploy"
  environmentName: "prod"
  artifactName: "bicep-templates"
  location: ""
  locationAbbriviation: ""
  subscriptionId: ""

jobs:
  - job: publishbicep
    displayName: Publish bicep files as pipeline artifacts
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: DownloadPipelineArtifact@0
        displayName: "Download Artifact: ${{ parameters.artifactName }}"
        inputs:
          artifactName: "${{ parameters.artifactName }}"
          targetPath: $(System.ArtifactsDirectory)/${{ parameters.artifactName }}

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploy Main Template
        inputs:
          azureResourceManagerConnection: '${{ parameters.seriviceConnectionName }}'
          deploymentScope: 'Subscription'
          subscriptionId: '${{ parameters.subscriptionId }}'
          location: ${{ parameters.location }}
          templateLocation: 'Linked artifact'
          csmFile: '$(System.ArtifactsDirectory)/${{ parameters.artifactName }}/main.json'
          overrideParameters: -locationAbbriviation ${{parameters.locationAbbriviation}}
          deploymentMode: 'Incremental'
