parameters:
  seriviceConnectionName: ""
  systemName: "demodeploy"
  environmentName: "prod"
  artifactName: "bicep-templates"
  location: ""
  locationAbbriviation: ""
  subscriptionId: ""

jobs:
  - job: publishbicep
    displayName: Publish bicep files as pipeline artifacts
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: PowerShell@2
        displayName: Bicep Build
        inputs:
          targetType: 'inline'
          script: |
            az bicep build --file 'deployment/main.bicep'
            az bicep build --file 'deployment/trafficmgr.bicep'
          pwsh: true

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Validate ARM Template
        inputs:
          azureResourceManagerConnection: ${{ parameters.seriviceConnectionName }}
          deploymentScope: 'Subscription'
          subscriptionId: '${{ parameters.subscriptionId }}'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: 'deployment/main.json'
          overrideParameters: -locationAbbriviation ${{parameters.locationAbbriviation}}
          deploymentMode: 'Validation'

      - task: CopyFiles@2
        displayName: 'Copy templates to $(Build.ArtifactStagingDirectory)/${{parameters.artifactName}}'
        inputs:
          SourceFolder: "deployment"
          Contents: '*.json'
          TargetFolder: "$(Build.ArtifactStagingDirectory)/${{parameters.artifactName}}"

      - task: PublishPipelineArtifact@1
        displayName: "Publish Pipeline Artifact"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/${{parameters.artifactName}}"
          artifact: "${{parameters.artifactName}}"
