parameters:
  seriviceConnectionName: ""
  systemName: "demodeploy"
  environmentName: "prod"
  artifactName: "bicep-templates"
  location: ""
  locationAbbriviation: ""

jobs:
  - job: publishbicep
    displayName: Publish bicep files as pipeline artifacts
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: CopyFiles@2
        displayName: "Copy bicep files to: $(Build.ArtifactStagingDirectory)/${{parameters.artifactName}}"
        inputs:
          SourceFolder: "deployment"
          Contents: "**/*.bicep"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/${{parameters.artifactName}}"

      - task: AzureCLI@2
        displayName: Azure CLI - Create resource group ${{parameters.systemName}}-${{parameters.environmentName}}-${{parameters.locationAbbriviation}}
        inputs:
          azureSubscription: ${{ parameters.seriviceConnectionName }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az group create -l "${{parameters.location}}" -n "${{parameters.systemName}}-${{parameters.environmentName}}-${{parameters.locationAbbriviation}}"

      - task: AzureCLI@2
        displayName: Azure CLI - Validate bicep template
        inputs:
          azureSubscription: ${{ parameters.seriviceConnectionName }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group validate `
            --template-file "$(System.ArtifactsDirectory)/${{ parameters.artifactName }}/main.bicep" `
            --resource-group "${{parameters.systemName}}-${{parameters.environmentName}}-${{parameters.locationAbbriviation}}" `
            --parameters locationAbbriviation=${{parameters.locationAbbriviation}}

      - task: PublishPipelineArtifact@1
        displayName: "Publish Pipeline Artifact"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/${{parameters.artifactName}}"
          artifact: "${{parameters.artifactName}}"
