parameters:
  seriviceConnectionName: ""
  systemName: "demodeploy"
  environmentName: "prod"
  artifactName: "bicep-templates"
  location: ""

jobs:
  - job: trafficmanager
    displayName: Create traffic manager
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: DownloadPipelineArtifact@0
        displayName: "Download Artifact: ${{ parameters.artifactName }}"
        inputs:
          artifactName: "${{ parameters.artifactName }}"
          targetPath: $(System.ArtifactsDirectory)/${{ parameters.artifactName }}

      - task: AzureCLI@2
        displayName: Azure CLI - Create resource group ${{parameters.systemName}}-${{parameters.environmentName}}
        inputs:
          azureSubscription: ${{ parameters.seriviceConnectionName }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az group create -l "${{parameters.location}}" -n "${{parameters.systemName}}-${{parameters.environmentName}}"

      - task: AzureCLI@2
        displayName: Azure CLI - Deploy Bicep
        inputs:
          azureSubscription: ${{ parameters.seriviceConnectionName }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az deployment group create `
            --template-file "$(System.ArtifactsDirectory)/${{ parameters.artifactName }}/trafficmgr.bicep" `
            --resource-group "${{parameters.systemName}}-${{parameters.environmentName}}"
